name: CI

on: push
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo OK
  e2e_tests:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo 1

  release:
    runs-on: ubuntu-latest
    needs:
      - unit_tests
    steps:
      - name: Trigger deploybot
        env:
          USER_EMAIL: a
          FALLBACK_EMAIL: b
        run: |
          HTTP_CODE='0'

          triggerDeployment () {
            local EMAIL=$1
            HTTP_CODE=`curl -s -o /dev/null -X GET -w ''%{http_code}'' https://dummy.restapiexample.com/api/v1/employee/1`
            echo "https://dummy.restapiexample.com responded with HTTP Status $HTTP_CODE"
          }

          echo "Attempt with fallback email: $USER_EMAIL"
          triggerDeployment $USER_EMAIL

          if [[ "$HTTP_CODE" != "200" ]]; then
            if [[ "$HTTP_CODE" == "422" ]]; then
              echo "Attempt with fallback email: $FALLBACK_EMAIL"
              triggerDeployment $FALLBACK_EMAIL
            fi

            if [[ "$HTTP_CODE" != "200" ]]; then
              exit 1
            fi
          fi
      
