name: CI

on: push
jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo OK
  e2e_tests:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo 1

  release:
    runs-on: ubuntu-latest
    needs:
      - unit_tests
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          required_contexts: 'E2E tests,Unit tests'
          environment: 'temploy'
          description: 'We are the ones [google](google.pl)'
          transient_environment: true
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
