name: CI

on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          required_contexts: ''
          environment: 'temploy'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
