name: Deployment

on:
  deployment

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/set-deployment-status@v1
        with:
          state: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Execute deployment'
        run: echo 'OK'
      - uses: avakar/set-deployment-status@v1
        with:
          state: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
