name: Deployment

on:
  deployment

jobs:
  execute:
    if: github.event.deployment.environment == 'temploy'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: avakar/set-deployment-status@v1
        with:
          state: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Execute deployment'
        run: echo ok
      - uses: avakar/set-deployment-status@v1
        with:
          state: success
          environment_url: https://google.pl
          description: 'We are the ones [google](google.pl)'
          auto_inactive: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: avakar/set-deployment-status@v1
        if: ${{ failure() }}
        with:
          state: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
